### ISSUE TITLE
rename module

### ISSUE THREAD

**Issue by boneskull** [andreogle/gulp-eslint-teamcity-formatter#1]
this module doesn't actually have anything to do with gulp, and can be used on the CLI directly, or with grunt-eslint, etc.

**Comment by andreogle** [comment]
fair enough. any suggestions? eslint-teamcity-formatter?

**Comment by boneskull** [comment]
@andreogle LGTM :smile:

**Comment by andreogle** [comment]
Ok cool. Will get on it shortly :+1:

**Comment by andreogle** [comment]
I went with "eslint-teamcity" as the new name. Thought it might be slightly easier to find.

The renamed project can been found [here](https://github.com/andreogle/eslint-teamcity)

**Comment by boneskull** [comment]
tyvm

**Comment by boneskull** [comment]
@andreogle You may want to deprecate this package with the message to use the other one.  `npm deprecate`

**Comment by andreogle** [comment]
didn't know about npm deprecate, will do it now. thanks!
